- _layouts/post.html
When `url` and `identifier` are not defined, the Disqus embed use the window URL as identifier when creating a thread, which is causing duplicate "split threads". :bowtie: 
I am not sure if this will remove the old comments, but it will avoid the "split threads" in the feature. 🤔 
More info:
https://help.disqus.com/customer/en/portal/articles/2158629
> Set `url` and `identifier` in disqus

- Gemfile
- Gemfile.lock
- _config.yml
Now we are able to write Emojis with the same syntax we use in Github. 🎉
> Add Jemoji for supporting GitHub-flavored Emojis

- _posts/deployments/2017-07-04-post-mortem-1.html
- _posts/deployments/2017-07-19-post-mortem-2.html
- _posts/deployments/2017-08-28-post-mortem-3.html
- _posts/deployments/2017-12-15-post-mortem-4.html
That way they are highlighted differently and thus easier to distinguish
from other topics.
> Mark post mortems as 'deployments' blog posts

- _posts/development/2018-06-01-sprint-report-39.md
It was not added in https://github.com/openSUSE/obs-landing/pull/163
> Add openSUSE conference to last sprint report

- _includes/post-listing.html
- _posts/deployments/2017-08-28-post-mortem-3.html
- _posts/development/2017-05-05-frontend-sprint-report-1.html
- _posts/development/2017-08-18-sprint-report-22.md
- _posts/development/2017-12-20-summary-of-2017.md
- _posts/documentation/2017-05-15-creating-your-own-image-template.md
- _posts/documentation/2018-05-09-container-building-and-distribution.md
- _posts/releases/2018-03-19-release_of_obs_2.9.md
Using the post.content we are just render the first 75 words without taken into account if they include things like code and titles, which shouldn't be in the post description.
With post excerpts we can decided what is shown for every blog post (using the `` tag):
https://jekyllrb.com/docs/posts/#post-excerpts
This is how it looks like now: :tada:
>  Use post excerpts in the blog post list

- _posts/development/2017-09-04-sprint-report-8.md
- _posts/releases/2016-07-05-download-on-demand-feature.md
- _posts/releases/2016-10-21-information-about-constraints-problems.md
- _posts/releases/2017-03-14-osc-0.157.1-release.md
Add description to Sprint 23 & disable excerpts for blog posts without introduction :bowtie:
> Fix blog post without description in blog posts list

- README.md
We missed more details about documentation deployment. Extended here and
linked to «obs-docu» for the first steps to follow.
> Extend deployment instructions

- _includes/rss-feed.rss
- _plugins/emojify.rb
- feed.rss
That's according to atom spec, html should be escaped there
> Escape html in feed summary

- _posts/development/2020-06-10-events-to-notifications.md
Nothing major, just minor possible improvements I've found our last blog post.
> Fix typos in events-to-notifications blog post

- support/index.html
openFATE has been discontinued and should no longer be linked to as there is no archive.
This fixes #237.
> Remove mentions of openFATE on support page

- _posts/development/2021-02-18-introducing-flatpak-builds.md
Just something I've noticed while reading the blog post.
> Fix capitalization in "Introduction Flatpak Builds" blog post

- _includes/partials/_how-to-give-us-feedback.md
- _includes/partials/_revamping-ui-what-is-coming-next.md
- _includes/partials/_team_gallery.html
- _layouts/default.html
- _posts/development/2018-10-05-revamping-ui.md
- _posts/development/2019-08-12-address-typography-issues.md
- _posts/development/2019-08-27-address-typography-issues-part-02.md
- _posts/development/2020-02-17-mobile-first-layout.md
- _posts/development/2020-03-03-who-said-obs-was-unusable.md
- _posts/development/2020-03-24-notifications-redesign.md
- _posts/development/2020-04-06-rails6.md
- _posts/development/2020-04-27-notifications-round-two.md
- _posts/project/2019-05-14-build-solutions-team.md
- _posts/releases/2008-06-11-version-1.0-rc1.html
- _posts/releases/2009-03-19-version-1.5.html
```
The opensuse-buildservice channel moved to the Libera.Chat network.
The capitalization of "Libera.Chat" is in line with the one used in
the open-build-service git repo.
```
> Point to the IRC channel on the Libera.Chat network

- _config.yml
Brokens links were the "Share Twitter" button at the bottom of every blog post and links in the RSS feed. In Jekyll <4.2, the value of `site.url` defaults to `0.0.0.0:4000` when the website is generated in the development environment.
Before, the RSS feed with broken links which don't contain the domain:
```xml
<entry>
<title>A Bit of Action for Pull/Merge Requests and the Tokens UI</title>
<link href="/2021/09/14/scm-more-pull-request-actions-and-ui//"/>
<updated>2021-09-14T00:00:00+00:00</updated>
<id>/2021/09/14/scm-more-pull-request-actions-and-ui//</id>
<summary type="html">After a quiet vacation month in August, we’re back with changes to improve workflows in the integration between OBS and source code management systems (SCM) like GitHub and GitLab. Workflows are cleaning up after …
```
> Set site.url to fix broken links

- _config.yml
Also: Future was enabled in the deployment settings, it's removed now.
> Fix site.url config

- update_documentation.sh
This makes the script more portable on non-openSUSE systems which rely on cloning the daps2docker repository to use daps2docker. Symlinking _daps2docker.sh_ to somewhere in the $PATH works in this case.
> Use daps2docker from $PATH

- update_documentation.sh
This submodule is updated in update_documentation.sh, but the changes were never added to the commit.
> Add open-build-service-documentation to 'git add' command in update_documentation.sh

- _posts/development/2021-08-02-link-package-configure-repositories-and-ui.md
While users should always refer to the user documentation as the sole source of truth, some might still refer to this blog post. To prevent misunderstands and issues, we point them to the user documentation.
Updating old blog posts whenever a step changes doesn't scale and it's easy to forget.
Preview of the changes:
> Replace outdated documentation with a link to user documentation

- _posts/development/2022-03-17-beta-features-management.md
This is the official blog post on the changes introduced to allow users to manage beta features. The blog post on the beta program, which is referred in all other blog posts, is updated in this other PR: https://github.com/openSUSE/obs-landing/pull/347
> Announce management of beta features

- Gemfile
- Gemfile.lock
- _config.yml
- _layouts/default.html
- _posts/development/2022-04-04-scm-integration-trigger_services.md
- stylesheets/pygments-default.css
With an example for YAML. It's as simple as passing the language in blocks of backticks.
The stylesheet is the default from Pygments at https://pygments.org/demo/.
Preview:
> Setup syntax highlighting for code examples

- .gitignore
- Gemfile
- Gemfile.lock
- docker-compose.override.yml.example
- docker-compose.yml
The jekyll docker image switched to Ruby 3. Make our bundle work with that version. Also introduces docker-compose.override.yml if your UID/GID is not 1000:100
> Bugfix dev env

- _includes/partials/_series-of-posts-about-scm-integration.md
- _posts/development/2022-06-20-token-sharing.md
The missing `include` was also added to the latest blog post `Token Party!`.
Preview of the changes (highlighted in red):
> Add 2 latest blog posts in series of SCM/CI integration

- stylesheets/app.css
As it is, pre content tends to overflow outside of the post
> Improve display of pre in .post-content

- _posts/development/2021-01-26-api-documentation-remake.md
- _posts/development/2021-04-12-api-docs-workers-and-build.md
- _posts/development/2021-10-12-notifications-group-filter.md
- _posts/development/2021-12-09-api-docs-sources-and-search.md
- _posts/development/2022-08-29-api-docs-search.md
- _posts/documentation/2022-10-10-more-api-docs-sources.md
- _posts/documentation/2023-03-21-continuing-api-docs-sources.md
- _posts/documentation/2023-05-02-api-docs-comments-status-staging.md
This integrates changes from https://github.com/openSUSE/obs-docu/pull/286, and changes the remaining links on the page to the new apidocs urls. I also included fixes to the script for updating documentation
> Change the links to the new apidocs url

- help/manuals/obs-admin-guide/obs.cha.security_concepts.html
Proposing some small typo updates to the "Signature Handling" section.
> Small typo updates to the Security Concepts page

- _posts/deployments/MARKDOWN_TEMPLATE
An example of a post mortem for an imaginary service degradation with comments on what the individual sections are about.
This lived in the wiki in a weird format so far...
https://github.com/openSUSE/open-build-service/wiki/Post-Mortem-Template/
But we only ever will write post mortems here.
> Add Post Mortem template

- _layouts/default.html
Closes: #442
When we paste a link to our blog post on social media, its appearance is determined by the OpenGraph metadata we set on our HTML (PR #395).
One of the OpenGraph tags we can set is `og:url` (the URL of the content).
So far the value has been incorrect. Having URLs like
```
https://openbuildservice.org/_posts/development/2023-11-30-whatnot.md
```
where we should have
```
https://openbuildservice.org/2023/11/30/whatnot/
```
Jekyll provides the `page`  Liquid variable with both `page.path` and `page.url` properties. `page.url` is the one we need. Read the differences [here](https://jekyllrb.com/docs/variables/#page-variables). 
Check the page source of the deploy preview or on localhost:4000 and search for `og:url`, it should contain the correct URL now.
> Fix OpenGraph URL metadata (og:url)

- Gemfile.lock
Depends on https://github.com/openSUSE/obs-landing/pull/493 because updating nokogiri >= 1.18 requires ruby >= 3.1.0
---
https://github.com/openSUSE/obs-landing/security/dependabot/29
libxml2 v2.12.7 addresses https://github.com/advisories/GHSA-vv62-jfwq-693v:
described at https://gitlab.gnome.org/GNOME/libxml2/-/issues/720
patched by https://gitlab.gnome.org/GNOME/libxml2/-/commit/2876ac53
---
https://github.com/openSUSE/obs-landing/security/dependabot/38
libxml2 v2.13.6 addresses:
https://github.com/advisories/GHSA-fgfv-9xqc-v794
described at https://gitlab.gnome.org/GNOME/libxml2/-/issues/847
https://github.com/advisories/GHSA-m366-8h8r-6fqr
described at https://gitlab.gnome.org/GNOME/libxml2/-/issues/828
---
https://github.com/openSUSE/obs-landing/security/dependabot/40
libxslt …
> Bump nokogiri to 1.18.8

- _posts/development/2025-01-21-project-labels.md
- _posts/development/2025-05-15-foster-collaboration.md
> Fix typo: "beta programs" -> "beta program" (II)
