_posts/releases/2016-07-05-download-on-demand-feature.md

Make headlines of DoD blog post smaller

---

_posts/releases/2017-03-14-osc-0.157.1-release.md

blog post about the new osc-0.157.1 release

blog entry about new osc release 0.157.1

---

_posts/in_the_press/2017-04-01-Microsoft-acquires-Open Build-Service-to-integrate-it-into-Visual-Studio.md

Add blog post to announce that Microsoft acquires Open Build Service to integrate it into Visual Studio. :tada:

Add blog post: OBS sold to Microsoft

---

download/index.html
download/other/index.html

2.8 got released, so the links needed to be updated. :bowtie:

Update links to point to 2.8

---

_posts/releases/2017-04-07-version-2.8.md

https://trello.com/c/NVHM3zTS/337-5-p3-release-announcement-2-8

Blog post to announce obs version 2.8

---

_posts/releases/2017-05-11-new-image-templates-page.md

Formating the list properly didn't work. So we have to format the text
in a different way.

Update template docu

---

_posts/development/2017-06-26-sprint-report-4.md

Remove unneeded bullet point and add a separation line. :confounded:

Improve Sprint report

---

_posts/deployments/2017-07-19-post-mortem-2.html

We had some issues during our last deployment, which caused the deployment
to take longer than expected.
This documents what has happened.

Post mortem for delayed deployment on 19th July of 2017

---

_posts/development/2017-09-19-sprint-report-9.md

* Added sprint report
* Fix formatting and spelling

Add sprint report for Sprint 24

---

README.md
_posts/documentation/2017-09-22-two-new-guides-for-builders.md
stylesheets/obs.css

since @adrianschroeter  asked us to make a post about the docs...
it would be ideal if you could update the published documentation when this goes live, since we've corrected a few references to our example users

blog post about updated docs

---

feed.rss

This allows to read blog articles in RSS feed reader directly.

Do not truncate articles in RSS feed

---

_includes/appliance_config.inc
about/index.html
help/index.html
index.html

most are straightforward
I'm just not totally sure about the added commas

Fix grammar and a typo

---

_posts/deployments/2017-12-15-post-mortem-4.html

Blog post about 14th December's deployment problems.
This PR supersedes #97.

Post mortem of deployment in 14th December

---

team/index.html

Add description of my self to the team page. :bowtie:

Add description of Ana

---

_layouts/post.html
stylesheets/app.css

Make easier to share the posts on Twitter. :bowtie:

Add Share on Twitter button

---

team/index.html

- Add description of my self to the team page.

Add description of Eduardo

---

_posts/deployments/2018-01-17-post-mortem-5.html

Today we had some issues after the deployment. This blog explains
what happened.
Co-written with @DavidKang

Post-mortem: Deployment on January 17th, 2018

---

download/index.html

By now the most current version is Leap 42.3

Update leap version on download page

---

_posts/development/2018-02-12-sprint-report-31.md

Sprint report 31

---

_posts/development/2018-02-12-sprint-report-31.md

I do not know how to write author 🙈

Correct label in post: autor -> author

---

_layouts/post.html

Improve dates format in posts

---

_posts/development/2018-03-01-cloud-upload.md

In the last blog post about cloud upload. :see_no_evil:

Correct typo :see_no_evil:

---

team/index.html

add twitter link for Marco

---

_includes/post-listing.html
_layouts/post.html

 Use Jekyll date filters to output ordinal dates

---

README.md

We are using bundle and it is not true that it is enough with installing Jekyll. :bowtie:

Update local preview documentation

---

_posts/documentation/2018-05-09-container-building-and-distribution.md

THX to @wfeldt for his comment

fix typo 'exiting' > 'existing'

---

_posts/deployments/2017-12-15-post-mortem-4.html
_posts/deployments/2018-03-16-post-mortem-5.md
_posts/deployments/2018-03-23-post-mortem-6.md
_posts/documentation/2017-09-27-suse-studio-express.md
_posts/documentation/2018-05-09-container-building-and-distribution.md
_posts/releases/2017-04-07-version-2.8.md
_posts/releases/2018-03-19-release_of_obs_2.9.md

 Remove OBS Team as author

---

_posts/development/2017-05-05-frontend-sprint-report-1.html

How can it be that nobody has realised before? It is not small :rofl:

Sprint 15 looked broken because of non closed h2 tag

---

_posts/documentation/2018-05-26-branch-container-with-osc-cheatsheet.md

Introduced in https://github.com/openSUSE/obs-landing/pull/161 :see_no_evil:

Remove OBS Team as author again

---

_posts/development/2018-07-17-sprint-report-41-42.md

Co-authored-by: Björn Geuken <bgeuken@suse.de>
Co-authored-by: Christian Bruckmayer <cbruckmayer@suse.com>
Co-authored-by: David Kang <dkang@suse.com>
Co-authored-by: Eduardo Navarro <enavarro@suse.com>
Co-authored-by: Henne Vogelsang <hvogel@opensuse.org>
Co-authored-by: Victor Pereira <vpereira@suse.com>

Add Sprint report for Sprint 41 & 42

---

_posts/development/2018-08-02-cloud-upload-azure.md

Something we missed in the review.

Use the same author as previous blog posts

---

_posts/development/2018-08-15-sprint-report-44.md

Co-authored-by: Björn Geuken <bgeuken@suse.de>
Co-authored-by: Dany Marcoux <dmarcoux@suse.com>
Co-authored-by: David Kang <dkang@suse.com>
Co-authored-by: Eduardo Navarro <enavarro@suse.com>
Co-authored-by: Henne Vogelsang <hvogel@opensuse.org>
Co-authored-by: Moisés Déniz Alemán <mdeniz@suse.com>
Co-authored-by: Saray Cabrera Padrón <scabrerapadron@suse.de>
Co-authored-by: Victor Pereira <vpereira@suse.com>

Add sprint report 44

---

stylesheets/app.css

Fix tiny fonts in lists

---

_posts/development/2019-02-15-revamping-request-ui.md

Add some more details and mention the help we got from upstream.
Sorry I didn't add this before. I had RAM problems in my computer when trying to get the performance numbers. We decided not to mention the numbers, as this page is faster than before but still there is place for improvement and it is slower than the old one (because of the improvement in usability - Nice table with first column fixed instead of a broken table)

Improve monitor section in the last blog post

---

_includes/partials/_team_gallery.html
_posts/project/2019-05-14-build-solutions-team.md

Other teams and collaborators wanted to have a clearer understanding of
what we do and how we do it.

Add blog post with detailed information about Build Solutions team

---

_posts/development/2019-12-20-year-end-post.md

Look back at 2019! :tada: 
Co-authored-by: David Kang <dkang@suse.com>

Add 2019 year-end blog post

---

_posts/development/2020-02-17-mobile-first-layout.md

This is about mobile first design, not progressive enhancement

Fix image description

---

_posts/deployments/2020-04-08-post-mortem.md

Co-authored-by: Daniel Donisa <daniel.donisa@suse.com>
Co-authored-by: Eduardo Navarro <enavarro@suse.com>
Co-authored-by: Lukas Krause <lkrause@suse.de>

Post mortem about yesterdays degradation

---

_posts/development/2021-02-15-notifications-new-filters.md

Just found some tiny typos :slightly_smiling_face:

Fix typos in notifications-new-filters blog post

---

_posts/development/2021-05-31-scm-integration.md
_posts/development/2021-08-02-link-package-configure-repositories-and-ui.md

Once this is merged, we need to communicate this through our usual communication channels.

Update blog posts for target_project changes in {link,branch}_package steps

---

README.md

Rephrase paragraph and add troubleshooting section

Update documentation section in README.md

---

_posts/development/2021-11-22-scm-workflow-runs.md

Following feedback from this [comment](https://github.com/openSUSE/open-build-service/issues/11665#issuecomment-977842325).

Clarify how push events for tags are working

---

update_documentation.sh

To make this usable on non-openSUSE systems.

Make update_documentation.sh more portable

---

Gemfile
Gemfile.lock
_config.yml
_includes/post-listing.html
blog/index.html
stylesheets/app.css

Paginate the blog's index page

---

_includes/partials/_series-of-posts-about-scm-integration.md
_posts/development/2022-04-04-scm-integration-trigger_services.md

It's intentional to not mention the other changes like bug fixes or documentation.

Write blog post about trigger_services step

---

index.html

Website text suggestions mentioned in #390 and a few more I just noticed.

Bottom blurb

---

_posts/deployments/MARKDOWN_TEMPLATE

While reading the template I found a few typos and expressions to be improved.

Add some corrections to the post-mortem template

---

CONTRIBUTING.md
_posts/HTML_TEMPLATE
_posts/KRAMDOWN_TEMPLATE
_posts/MARKDOWN_TEMPLATE
_posts/deployments/MARKDOWN_TEMPLATE

Extend the How To section of the Contributing document.

Explain how to add page images for social media

---

_posts/project/2019-05-14-build-solutions-team.md
team/index.html

Tomorrow is my last work day in the team, so I send this PR to remove myself from the team. I know that I could stay there since I contributed to the project for many years, but I prefer not to.

Remove myself from the team

---

download/index.html

OBS `2.10` in on already on OpenSUSE Leap `15.6`

Update matching version
